### ISSUE TITLE
Add Northern NJ and Lower Hudson Valley regions

### ISSUE THREAD

**Issue by nwshane** [NY-Vipassana-Association/grassroots-map#3]
We currently only display the five boroughs on the map. Before we release, we should add:

- the Northern NJ region, with regional organizer Vikas's contact info
- the Lower Hudson Valley region

We display the five NYC boroughs by grabbing data for their shapes/borders from [this URL](http://data.beta.nyc//dataset/68c0332f-c3bb-4a78-a0c1-32af515892d6/resource/7c164faa-4458-4ff2-9ef0-09db00b509ef/download/42c737fd496f4d6683bba25fb0e86e1dnycboroughboundaries.geojson). 

Todo: 
- [x] Investigate: Are there similar geojson data that exist for northern NJ and the lower Hudson Valley? We need to determine some way to display these regions.
- [x] Add the regions to the map
- [x] add Vikas's contact info

**Comment by nwshane** [comment]
@jfw305 shall I combine some of [these counties](http://data.ci.newark.nj.us/dataset/new-jersey-counties-polygon/resource/95db8cad-3a8c-41a4-b8b1-4991990f07f3) in northern NJ to create a map region for northern NJ? If so, which counties should I include?

**Comment by jfw305** [comment]
Hey!

Again sorry for the delay! Got wrapped up in the holiday period with family.

That's a great website you found with the map. Let's include all counties upto and including Edison, NJ.

Also wanted to put it on your radar that there is a new group sitting in NJ and most likely one in Queens as well. I'll forward you the info on these in separate emails.

Anything I can do to help with getting the website published?

Hope you've had a wonderful start to 2019!

With much metta,
Jeremy
________________________________

**Comment by jfw305** [comment]
Thanks Nathan. I'll be sitting a 10-day course until the 20th. I'll check back in once I'm done.

There's a 2-day course taking place on February 1-3 that I'm serving. Are you interested in doing that with me? If so, you can sign up through the course schedule page.

Much metta,
Jeremy
________________________________

**Comment by nwshane** [comment]
Finished adding both regions
